version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    networks:
      - fororonk-network
  
  chat-app:
    container_name: chat-app
    build:
      context: ./chat-app
      dockerfile: Dockerfile
    ports:
      - 7001:7001
    networks:
      - fororonk-network

  chat-service-db:
    image: mysql:5.7.20
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 7200:3306
    volumes:
      - ./chat-service-db:/var/lib/mysql
    networks:
      - fororonk-network

  chat-service:
    container_name: chat-service
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - 7100:7100
    depends_on:
      - chat-service-db
    networks:
      - fororonk-network

  users-service-db:
    image: mysql:5.7.20
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 7201:3306
    volumes:
      - ./users-service-db:/var/lib/mysql
    networks:
      - fororonk-network

  users-service:
    container_name: users-service
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - 7101:7101
    depends_on:
      - users-service-db
    networks:
      - fororonk-network
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 7300:80
    depends_on:
      - users-service-db
      - chat-service-db
    volumes: 
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - fororonk-network


networks: 
  fororonk-network:
      driver: bridge